#ifndef __NA5TR1_H__
#define __NA5TR1_H__

#include "pinmacros.h"

/*
#define RF_UCRESET			P1_0
#define RF_TXRX				P1_3
#define RF_SPISSN			P2_6
#define RF_UCIRQ			P2_7
#define RF_PONRESET			P3_0
#define RF_LDO_CE			P4_2
#define RF_SPIRXD			P5_1
#define RF_SPITXD			P5_2
#define RF_SPICLK			P5_3
*/

MAKE_PORT_MACRO(RF_UCRESET,	1,0);
MAKE_PORT_MACRO(RF_TXRX,	1,3);
MAKE_PORT_MACRO(RF_SPISSN,	2,6);
MAKE_PORT_MACRO(RF_PONRESET,3,0);
MAKE_PORT_MACRO(RF_LDO_CE,	4,2);
MAKE_PORT_MACRO(RF_SPIRXD,	5,1);
MAKE_PORT_MACRO(RF_SPITXD,	5,2);
MAKE_PORT_MACRO(RF_SPICLK,	5,3);

MAKE_PORT_MACRO(RF_UCIRQ,		2,7);
MAKE_PORTINT_MACRO(RF_UCIRQ,	2,7);

#endif
