#-*-Makefile-*- vim:syntax=make

###############################################################################
# 
# Makefile for RETOS applications
#
###############################################################################

SRCS = mtsl.c 

id=1
com=1

# include application makerules
include ../../Makerules


